### ISSUE TITLE
water isotope package

### ISSUE THREAD

**Issue by bumbanian** [cran-task-views/Hydrology#105]
Hi folks - would like to suggest the following package for inclusion in your list, supports retrieval and analysis of water isotope data for hydro applications:

CRAN: https://cran.r-project.org/package=isoWater 
GitHub: https://github.com/SPATIAL-Lab/isoWater 

Thanks for maintaining this resource!

**Comment by boshek** [comment]
👋 @bumbanian. Thanks for letting us know! 

Can I ask that you contribute directly by opening a pull request? This [file](https://raw.githubusercontent.com/cran-task-views/Hydrology/main/Hydrology.md) is what you would edit and since no code is being run, you can edit directly into GitHub. That makes it easy and all captures your contribution.
